GET http://localhost:5000/Users

###

GET http://localhost:5000/Users/id/6609469809f7b0bbcbb185ac

### 

POST http://localhost:5000/Users
Content-Type: application/json

{
  "username": "CoderNamedNick",
  "email": "CoolApp@123.com",
  "password": "super-secret",
  "birthDate": "04/22/2003"
}

### 
GET http://localhost:5000/Users/username/CoderNamedNick


### 
GET http://localhost:5000/Users/email/coolapp@123.com

###
PATCH  http://localhost:5000/Users/id/6609469809f7b0bbcbb185ac
Content-Type: application/json

{
  "username": "CoderNamedNick"
}


###

DELETE http://localhost:5000/Users/id/6609469809f7b0bbcbb185ac

###

GET http://localhost:5000/Guilds

### 

POST http://localhost:5000/Guilds
Content-Type: application/json

{
  "guildName": "Example Guild4",
  "guildOwner": "6609469809f7b0bbcbb185ac", 
  "bio": "This is a description of the guild4."
}

###

DELETE http://localhost:5000/Guilds/id/