GET http://localhost:5000/Users

###

GET http://localhost:5000/Users/id/6609469809f7b0bbcbb185ac

### 

POST http://localhost:5000/Users
Content-Type: application/json

{
  "username": "CoderNamedNick",
  "email": "CoolApp@123.com",
  "password": "super-secret",
  "birthDate": "04/22/2003"
}

### 
GET http://localhost:5000/Users/username/CoderNamedNick

###
PATCH  http://localhost:5000/Users/id/6609469809f7b0bbcbb185ac
Content-Type: application/json

{
  "username": "CoderNamedNick"
}


###

DELETE http://localhost:5000/Users/id/6609469809f7b0bbcbb185ac